### PR TITLE
Feature/case studies

### PR DESCRIPTION
**Pull request by KamsiyonnaObi**
@brandonetter case studies page

### CODE REVIEW

**Comment by brandonetter** [comment]
The page itself looks good but your decoration on the text starts getting silly at mobile sizes:
image

**Comment by KamsiyonnaObi** [comment]
> The page itself looks good but your decoration on the text starts getting silly at mobile sizes: image

Yes do you have any suggestions that can help?

**Comment by brandonetter** [comment]
@KamsiyonnaObi What have you tried?

**Comment by KamsiyonnaObi** [comment]
> @KamsiyonnaObi What have you tried?

`w-fit` 🥲

I also wanted to make a whole new highlight for smaller devices, but I don't even know what causes the issue...

**Comment by brandonetter** [comment]
@KamsiyonnaObi Let me answer what's happening on discord

**Comment by KamsiyonnaObi** [comment]
> @KamsiyonnaObi Let me answer what's happening on discord

Thank you 👍🏽

**Pull request merged**
