### PR TITLE
feat: footer contact me

### PR DESCRIPTION
**Pull request by KamsiyonnaObi**
@brandonetter footer contact section

I also included code for including a background color to the project Card. Please I need help.

I changed the tailwind config file to create a new color class for the project cards but I have notice that for some reason Tailwind cannot read some of the color classes

For example `bg-Accent-Primary` works but bg-project-one doesn't

### CODE REVIEW

**Review by brandonetter — CHANGES_REQUESTED** [review]
image

This is working fine for me. Are you sure it wasn't a casing issue? Accent is capital but project is not.

## Issues:
1)  image

2)  image

1) Your hero section is causing everything to misalign. It also isn't centered at higher widths.
2) This icon isn't centered when hovered. 

- Use transitions for the hover animations on the icons, it's currently very jarring
- Your darkmode colors are off for the text

**Comment by KamsiyonnaObi** [comment]
Okay does `bg-project-one` work as the bg color of the projects Card? because I was trying to dynamically render a bg colour for the projects

**Comment by brandonetter** [comment]
@KamsiyonnaObi Okay i see the issue I think. I imagine you were trying to do something like:

```js
className={`bg-${projectId}`}
```

?

So you can't actually do this because tailwind doesn't create all the classes at once. It **reads** your files looking for classes and if it find them- it generates them. It doesn't know what `bg-${projectId}` this evaluates to, so it doesn't create any classes. If you want to use style dynamically you can do so with regular CSS classes defined in your globals.css or you can use some kind of logic that **includes** those names ahead of time.

If you define the CSS in tailwind.config it won't automatically generate them unless it sees them being used.

**Comment by brandonetter** [comment]
https://codesandbox.io/p/sandbox/musing-artem-xw734g

Here's a working example. 
I've added 2 classes to the globals.css that I use in `Dynamic2.tsx`
I've added 1 tailwind color extension to the tailwind config that I use in `Dynamic.tsx`

You can see in Dynamic.tsx that when I want to define some classes based on input- I'm actually explicitly writing out the entire class in text so that tailwind picks it up- because tailwind won't include any classes it doesn't see being used.

You can see in Dynamic2.tsx that because I'm just using regular CSS classes, I can dynamically make the names of the classes in code because those classes will be included no matter what.

**Comment by KamsiyonnaObi** [comment]
@brandonetter Ready to be reviewed 👍🏽

**Comment by brandonetter** [comment]
Looks good assuming the video you sent me is accurate :)

**Comment by KamsiyonnaObi** [comment]
I took out the animation lol. thank you 😄

**Pull request merged**
